Revert breaking change from 625c69e
interledgerjs/ilp-plugin-bells pull request #115
Opened 2017-03-23 15:57 UTC by michielbdejong

2017-03-23 15:59 UTC, michielbdejong commented
I was [adding `.account`](https://github.com/michielbdejong/ilp-client/blob/master/src/index.js#L384-L385) to work around the bug your PR fixed. :)

2017-03-28 11:15 UTC, sharafian requested changes

2017-03-28 11:15 UTC, sharafian commented on src/lib/plugin.js
> +        delete message.account
This shouldn't modify its parameter

2017-03-28 11:15 UTC, sharafian commented on src/lib/plugin.js
> +        delete transfer.account
This shouldn't modify its parameter

2017-03-28 12:16 UTC, michielbdejong commented on src/lib/plugin.js
> +        delete message.account
Ah, right. Good point

2017-03-29 09:54 UTC, sharafian requested changes

2017-03-29 09:54 UTC, sharafian commented on src/lib/plugin.js
> +        const correctedMessage = Object.assign({}, message)
I think it'd be more readable to put that at the top of the function, instead of recursing

2017-03-29 09:54 UTC, sharafian commented on src/lib/plugin.js
> +        yield * this._sendMessage(correctedMessage)
This should just be `yield` instead of `yield  *`, if you want to await `_sendMessage`

2017-03-29 11:44 UTC, michielbdejong commented on src/lib/plugin.js
> +        delete message.account
Fixed by line 431 above

2017-03-29 11:44 UTC, michielbdejong commented on src/lib/plugin.js
> +        delete transfer.account
Fixed by line 485

2017-03-29 11:45 UTC, sharafian approved these changes

2017-03-29 11:45 UTC, merged