Fix websocket reconnection
interledgerjs/ilp-plugin-bells pull request #117
Opened 2017-03-30 14:08 UTC by emschwartz

* make sure that the ws connection is reopened when it drops
* only consider the plugin connected after it has sent the subscribe message and gotten a confirmation back

Once this is approved I'll also create a PR to patch the current version being used with ilp-kit

2017-03-30 14:23 UTC, sentientwaffle requested changes

2017-03-30 14:23 UTC, sentientwaffle commented on src/lib/plugin.js
> +const wsReconnectDelayMax = 300
`reconnect()`'s `initialDelay` and `maxDelay` parameters should be in milliseconds -- are 1ms and 300ms the intended values?

2017-03-30 14:23 UTC, sentientwaffle commented on src/lib/plugin.js
> +                    if (!this.connected) {
Why recheck `if (!this.connected) {` -- are you expecting it to have changed?

2017-03-30 14:32 UTC, emschwartz commented on src/lib/plugin.js
> +const wsReconnectDelayMax = 300
Yup

2017-03-30 14:34 UTC, emschwartz commented on src/lib/plugin.js
> +const wsReconnectDelayMax = 300
If the plugin is disconnected for any substantive amount of time it can cause a connector to lose money

2017-03-30 14:36 UTC, emschwartz commented on src/lib/plugin.js
> +                    if (!this.connected) {
Nope, fixed

2017-03-30 14:46 UTC, sharafian approved these changes

2017-03-30 14:46 UTC, sentientwaffle approved these changes

2017-04-05 16:45 UTC, emschwartz commented
Replaced by https://github.com/interledgerjs/ilp-plugin-bells/pull/119

2017-04-05 16:45 UTC, closed without merging