docs: fix readme instructions
interledgerjs/ilp-plugin-bells pull request #134
Opened 2017-06-06 12:32 UTC by michielbdejong

2017-06-06 12:33 UTC, michielbdejong commented
@dappelt any other inaccuracies you found? I just tried out the instructions and could only find this one.

2017-06-06 12:39 UTC, emschwartz requested changes

2017-06-06 12:39 UTC, emschwartz commented on README.md
> +npm install --save ilp-core ilp-plugin-bells
The example should be updated to use the `ilp` module instead of `ilp-core`

2017-06-19 10:16 UTC, emschwartz approved these changes

2017-06-20 08:33 UTC, merged