Get service endpoints from ledger metadata
interledgerjs/ilp-plugin-bells pull request #52
Opened 2016-09-26 10:07 UTC by emschwartz

To be more flexible and RESTful the plugin should use the `urls` returned in the ledger metadata instead of assuming where the ledger endpoints are hosted relative to the base URL.

Thanks to @bensharaf for refactoring the tests into separate files. This makes it easier to add new tests.

Resolves https://github.com/interledger/js-ilp-plugin-bells/issues/48

2016-09-26 13:17 UTC, justmoon commented on src/lib/plugin.js
> +    this.urls = ledgerMetadata.urls
You should sanitize this object, before making it part of the plugin's state. Something like this:

``` js
this.urls = {
  account_transfers: ledgerMetadata.account_transfers,
  //...
}

// Check required ledger endpoints are present
if (typeof this.urls.account_transfers !== 'string') {
  throw new Error('...')
}
```

It's better to fail when connecting if we can than at some random later time.

2016-09-26 13:21 UTC, justmoon commented on test/connectSpec.js
> +    it('should set urls from object in metadata', function * () {
Should also test that no unexpected extra properties make it into `plugin.urls`.

2016-09-26 13:23 UTC, justmoon commented on test/connectSpec.js
> +      nock('http://red.example')
Should assert that these nocks are done on `afterEach`.

2016-09-26 13:24 UTC, justmoon requested changes

2016-09-26 14:17 UTC, emschwartz commented on test/connectSpec.js
> +      nock('http://red.example')
See https://github.com/interledger/js-ilp-plugin-bells/blob/urls-from-metadata/test/connectSpec.js#L33

2016-09-26 17:28 UTC, emschwartz commented on test/connectSpec.js
> +    it('should set urls from object in metadata', function * () {
Fixed in https://github.com/interledger/js-ilp-plugin-bells/pull/52/commits/71ee1b7e82db7817f3be32da6345943605cb7de8

2016-09-26 17:28 UTC, emschwartz commented on src/lib/plugin.js
> +    this.urls = ledgerMetadata.urls
Addressed in https://github.com/interledger/js-ilp-plugin-bells/pull/52/commits/71ee1b7e82db7817f3be32da6345943605cb7de8

2016-09-27 15:25 UTC, justmoon requested changes

2016-09-27 15:25 UTC, justmoon commented on test/connectSpec.js
> +function * assertRejectsWith (promise, errorConstructor, errorMessage) {
Use `chai-as-promised`.

2016-09-27 16:04 UTC, emschwartz commented on test/connectSpec.js
> +function * assertRejectsWith (promise, errorConstructor, errorMessage) {
Addressed in https://github.com/interledger/js-ilp-plugin-bells/pull/52/commits/24328b6e34c5f570f1b0c224861b8fcf3ac15e14

2016-09-27 16:05 UTC, justmoon approved these changes

2016-09-27 16:26 UTC, merged