feat: [BREAKING] s/send/sendTransfer; add sendMessage, incoming_message
interledgerjs/ilp-plugin-bells pull request #58
Opened 2016-10-17 17:45 UTC by sentientwaffle

2016-10-18 14:40 UTC, emschwartz requested changes

2016-10-18 14:40 UTC, emschwartz commented on src/lib/plugin.js
> +    }
Shouldn't these be in the (now empty) `_validateMessage` function?

2016-10-18 14:40 UTC, emschwartz commented on test/notificationSpec.js
> +      sinon.assert.calledOnce(this.stubIncomingMessage)
You should also check what those functions are called with

2016-10-18 14:57 UTC, sentientwaffle commented on src/lib/plugin.js
> +    }
`_validateMessage` is used by `_handleMessageNotification`, so that's a different set of checks.

2016-10-18 14:57 UTC, sentientwaffle commented on test/notificationSpec.js
> +      sinon.assert.calledOnce(this.stubIncomingMessage)
That's what the next line does: `sinon.assert.calledWith(this.stubIncomingMessage, this.message)`.

2016-10-18 15:05 UTC, emschwartz commented on src/lib/plugin.js
> +    }
Wouldn't it check the same things though?

2016-10-18 15:06 UTC, emschwartz commented on test/notificationSpec.js
> +      sinon.assert.calledOnce(this.stubIncomingMessage)
Sorry, missed that

2016-10-18 15:15 UTC, sentientwaffle commented on src/lib/plugin.js
> +    }
No, `sendMessage` expects `message.ledger` to be a ledger prefix. `_handleMessageNotification` expects it to be the ledger host.

2016-10-18 15:20 UTC, emschwartz commented on src/lib/plugin.js
> +    }
That's confusing, but ok

2016-10-18 15:20 UTC, emschwartz approved these changes

2016-10-19 13:16 UTC, emschwartz approved these changes

2016-10-20 15:21 UTC, merged